import javax.swing.*;
import java.awt.*;

/**
 * Created by amin on 12/23/14.
 */
public class CocoCrush {

    //    public static void main(String[] args) throws IOException {
//        JFrame frame = new JFrame("CocoCrush");
//        frame.setContentPane(new CocoCrush().jPanel);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//
//        GameController controller = new GameController();
//
//        panel.init (controller, engine);
//        controller.init (panel, engine);
//        controller.start ();
//
//    }
    JPanel jPanel;

//    public static void main(String[] args) {
//        JFrame frame = new JFrame("CocoCrush");
//        frame.setContentPane(new CocoCrush().jPanel);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.pack();
//        frame.setVisible(true);
//}

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGui();
            }
        });
    }

    private static void createAndShowGui() {
        JFrame frame = new JFrame("CandyCrush");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        GameEngine engine = new GameEngine();
        CocoCrush cocoCrush = new CocoCrush();
        GameController controller = new GameController();
        final GameBoard board = new GameBoard(controller, engine);
        engine.setGameBoard(board);
        cocoCrush.jPanel.addKeyListener(controller);
        cocoCrush.jPanel.add(board);
        frame.setContentPane(cocoCrush.jPanel);
        Thread gameloop = new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    board.repaint();
//                    System.out.println("asdfasdfasdfasdfadsfasdf");
                    try {
                        Thread.sleep(1000 / 30);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
        });
        gameloop.start();

        controller.init(board, engine);
        controller.start();

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        jPanel.setFocusable(true);
        jPanel.setRequestFocusEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
