import javax.swing.*;
import java.awt.*;

/**
 * Created by amin on 12/23/14.
 */
public class CocoCrush {

    JPanel jPanel;

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGui();
            }
        });
        System.out.println("Game Started");
    }

    public static void createAndShowGui() {
        JFrame frame = new JFrame("CandyCrush");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        String username = JOptionPane.showInputDialog(frame, "Please enter your name :", "CandyCrush", JOptionPane.PLAIN_MESSAGE);
        if (username.equals(""))
            username = "Player";
        GameEngine engine = new GameEngine(username);
        CocoCrush cocoCrush = new CocoCrush();
        final GameController controller = new GameController(frame);
        final GameBoard board = new GameBoard(controller, engine);
        engine.setGameBoard(board);
        cocoCrush.jPanel.addKeyListener(controller);
        cocoCrush.jPanel.add(board);
        frame.setContentPane(cocoCrush.jPanel);
        controller.init(board, engine);
        controller.start();

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        jPanel.setFocusable(true);
        jPanel.setRequestFocusEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
